"use client"

/**
 * The theme customiser's controls.
 *
 * Basic is a brand colour, a neutral and a corner radius; `lib/theme-generator.ts`
 * turns those into every token, and always passes contrast. Advanced is each
 * token by hand, scored against the same pairs CI enforces. Edits are stored and
 * applied at once: the site itself is the preview.
 *
 * a11y: the basic choices are radio groups. A swatch is painted in the primary
 * that family would give, which is guaranteed 3:1 against the panel, and the
 * current one is marked by a ring rather than a second colour.
 */

import { Collapsible } from "@base-ui-components/react/collapsible"
import { ChevronDownIcon, RotateCcwIcon } from "lucide-react"
import { useId, useMemo, useState } from "react"

// Generated by `scripts/extract-palettes.ts`, which the docs `registry` task
// runs. turbo.json makes typecheck, test and build depend on that task, because
// this is a static import and the file is gitignored.
import palettes from "@/.generated/palettes.json"
import {
  DEFAULT_RADIUS,
  RADII,
  customThemeCss,
  useCustomTheme,
  type CustomTheme,
  type Radius,
} from "@/lib/custom-theme"
import {
  contrastRatio,
  formatOklch,
  fromHex,
  parseOklch,
  toHex,
  type Oklch,
} from "@/lib/oklch"
import {
  BRAND_FAMILIES,
  DEFAULT_RECIPE,
  NEUTRAL_FAMILIES,
  brandColour,
  generateTheme,
  type Recipe,
} from "@/lib/theme-generator"
import {
  EDITABLE_TOKENS,
  checkPalette,
  type Palette,
  type TokenName,
} from "@/lib/theme-tokens"
import {
  DEFAULT_PRESET,
  SHIPPED_PRESETS,
  useActivePreset,
  useResolvedMode,
  type ShippedPreset,
} from "./theme-switcher"
import { CopyButton } from "./copy-button"
import { Badge } from "@registry/ui/badge"
import { Button } from "@registry/ui/button"
import { cn } from "@registry/lib/utils"

const shipped = palettes as Record<string, Palette>

/** A shipped preset as a starting point. The default is its own recipe (tested). */
export const seedFrom = (preset: ShippedPreset): CustomTheme => ({
  light: { ...shipped[`${preset}-light`]! },
  dark: { ...shipped[`${preset}-dark`]! },
  ...(preset === DEFAULT_PRESET ? { recipe: DEFAULT_RECIPE } : {}),
})

/** Human labels, so the fields do not read as raw custom property names. */
const TOKEN_LABELS: Record<TokenName, string> = {
  "--background": "Background",
  "--foreground": "Foreground",
  "--card": "Card",
  "--card-foreground": "Card foreground",
  "--popover": "Popover",
  "--popover-foreground": "Popover foreground",
  "--primary": "Primary",
  "--primary-foreground": "Primary foreground",
  "--secondary": "Secondary",
  "--secondary-foreground": "Secondary foreground",
  "--muted": "Muted",
  "--muted-foreground": "Muted foreground",
  "--accent": "Accent",
  "--accent-foreground": "Accent foreground",
  "--destructive": "Destructive",
  "--destructive-foreground": "Destructive foreground",
  "--border": "Border",
  "--input": "Input border",
  "--ring": "Focus ring",
}

const CHANNELS = [
  { key: "l", label: "L", name: "lightness", min: 0, max: 1, step: 0.005, places: 3 },
  { key: "c", label: "C", name: "chroma", min: 0, max: 0.37, step: 0.002, places: 3 },
  { key: "h", label: "H", name: "hue", min: 0, max: 360, step: 0.1, places: 1 },
] as const

const FOCUS_WITHIN = "has-[:focus-visible]:ring-ring has-[:focus-visible]:ring-2"

interface DraftFieldProps extends React.ComponentPropsWithoutRef<"input"> {
  /** The canonical text, shown whenever the field is not mid-edit. */
  value: string
  /** Called with the raw text; ignore anything that does not parse yet. */
  onCommit: (raw: string) => void
}

/**
 * An input that keeps what you typed until it parses.
 *
 * Half a hex code is not a colour, and neither is "0." — but both have to stay
 * on screen while you finish typing them. So the field holds its own draft, the
 * palette keeps the last value that parsed, and blurring throws an unfinished
 * draft away rather than leaving the field disagreeing with the swatch.
 */
function DraftField({ value, onCommit, className, ...props }: DraftFieldProps) {
  const [draft, setDraft] = useState<string | null>(null)

  return (
    <input
      {...props}
      value={draft ?? value}
      onChange={(event) => {
        setDraft(event.target.value)
        onCommit(event.target.value)
      }}
      onBlur={() => setDraft(null)}
      className={cn(
        "border-input bg-background focus-visible:ring-ring h-7 rounded-md border px-1.5 font-mono text-xs tabular-nums focus-visible:outline-none focus-visible:ring-2",
        className,
      )}
    />
  )
}

interface SegmentedProps<T extends string> {
  legend: string
  name: string
  value: T | undefined
  options: readonly { value: T; label: string }[]
  onChange: (next: T) => void
}

/** A radio group drawn as one row of segments. */
function Segmented<T extends string>({
  legend,
  name,
  value,
  options,
  onChange,
}: SegmentedProps<T>) {
  return (
    <fieldset>
      <legend className="mb-2 text-sm font-medium">{legend}</legend>
      <div className="border-border flex gap-0.5 rounded-lg border p-0.5">
        {options.map((option) => (
          <label
            key={option.value}
            className={cn(
              "flex h-8 flex-1 cursor-pointer items-center justify-center rounded-md text-xs transition-colors",
              FOCUS_WITHIN,
              value === option.value
                ? "bg-secondary text-secondary-foreground font-medium"
                : "text-muted-foreground hover:text-foreground",
            )}
          >
            <input
              type="radio"
              name={name}
              value={option.value}
              checked={value === option.value}
              onChange={() => onChange(option.value)}
              className="sr-only"
            />
            {option.label}
          </label>
        ))}
      </div>
    </fieldset>
  )
}

const capitalise = (word: string): string => word.charAt(0).toUpperCase() + word.slice(1)

const NEUTRAL_OPTIONS = NEUTRAL_FAMILIES.map((family) => ({
  value: family,
  label: capitalise(family),
}))

export function ThemeCustomiser() {
  const [stored, setStored] = useCustomTheme()
  const [preset, setPreset] = useActivePreset()
  const mode = useResolvedMode()
  const id = useId()

  // Until something is stored, start from what the site is already showing.
  const theme =
    stored ?? seedFrom(preset === "custom" ? DEFAULT_PRESET : (preset as ShippedPreset))
  const palette = theme[mode]
  const { recipe } = theme

  // The one write path: storing the theme and selecting the preset together
  // makes every control change the page at once. The radius carries over.
  const commit = (next: Omit<CustomTheme, "radius">, radius = theme.radius) => {
    setStored({ ...next, radius })
    if (preset !== "custom") setPreset("custom")
  }

  const applyRecipe = (next: Recipe) => {
    const generated = generateTheme(next)
    if (generated) commit({ ...generated, recipe: next })
  }

  // A hand-edited token drops the recipe: the palette is no longer generated.
  const setToken = (token: TokenName, colour: Oklch) => {
    commit({
      light: theme.light,
      dark: theme.dark,
      [mode]: { ...palette, [token]: formatOklch(colour) },
    })
  }

  // Without a recipe, the palette's own primary is the brand to show and keep.
  const brand = recipe?.brand ?? toHex({ ...parseOklch(theme.light["--primary"])!, a: 1 })
  const neutral = recipe?.neutral ?? DEFAULT_RECIPE.neutral
  const brandHex = toHex(brandColour(brand)!)

  // Each family's primary with the current neutral, in the mode on screen.
  const swatches = useMemo(
    () =>
      BRAND_FAMILIES.map((family) => ({
        family,
        colour: generateTheme({ brand: family, neutral })?.[mode]["--primary"],
      })),
    [neutral, mode],
  )

  const checks = useMemo(() => checkPalette(palette, contrastRatio), [palette])
  const failures = checks.filter((check) => !check.passes)
  const css = useMemo(() => customThemeCss(theme), [theme])

  return (
    <div className="flex flex-col gap-5">
      <fieldset>
        <legend className="mb-2 text-sm font-medium">Brand colour</legend>
        <div className="grid grid-cols-9 gap-1.5">
          {swatches.map(({ family, colour }) => (
            <label
              key={family}
              title={capitalise(family)}
              className={cn(
                "ring-offset-background flex aspect-square cursor-pointer rounded-full ring-offset-2",
                FOCUS_WITHIN,
                recipe?.brand === family &&
                  "ring-foreground has-[:focus-visible]:ring-foreground ring-2",
              )}
              style={{ background: colour }}
            >
              <input
                type="radio"
                name={`${id}-brand`}
                value={family}
                checked={recipe?.brand === family}
                onChange={() => applyRecipe({ brand: family, neutral })}
                aria-label={capitalise(family)}
                className="sr-only"
              />
            </label>
          ))}
        </div>
        <div className="mt-3 flex items-center gap-2">
          <label htmlFor={`${id}-brand-hex`} className="text-muted-foreground text-xs">
            Custom
          </label>
          <input
            type="color"
            aria-label="Custom colour picker"
            value={brandHex}
            onChange={(event) => applyRecipe({ brand: event.target.value, neutral })}
            className="border-input focus-visible:ring-ring ml-auto size-7 shrink-0 cursor-pointer rounded-md border bg-transparent p-0.5 focus-visible:outline-none focus-visible:ring-2"
          />
          <DraftField
            id={`${id}-brand-hex`}
            value={brandHex}
            onCommit={(raw) => {
              const next = fromHex(raw)
              // A brand is opaque, so drop any alpha the hex carries.
              if (next) applyRecipe({ brand: toHex({ ...next, a: 1 }), neutral })
            }}
            spellCheck={false}
            autoCapitalize="none"
            autoCorrect="off"
            maxLength={7}
            className="w-20 text-right"
          />
        </div>
      </fieldset>

      <Segmented
        legend="Neutral"
        name={`${id}-neutral`}
        value={recipe?.neutral}
        options={NEUTRAL_OPTIONS}
        onChange={(next) => applyRecipe({ brand, neutral: next })}
      />

      <Segmented<Radius>
        legend="Corners"
        name={`${id}-radius`}
        value={theme.radius ?? DEFAULT_RADIUS}
        options={RADII}
        onChange={(radius) => commit(theme, radius)}
      />

      <div className="flex flex-col gap-2">
        <Badge variant={failures.length ? "destructive" : "default"} size="sm">
          {failures.length === 0
            ? "All contrast checks pass"
            : `${failures.length} contrast ${failures.length === 1 ? "check fails" : "checks fail"}`}
        </Badge>
        {failures.length > 0 ? (
          <ul className="text-muted-foreground flex flex-col gap-1 text-xs">
            {failures.map((check) => (
              <li key={`${check.fg}-${check.bg}`} className="flex justify-between gap-2">
                <span>{check.label}</span>
                <span className="shrink-0 font-mono">
                  {check.ratio.toFixed(2)}:1 <span aria-hidden>·</span>{" "}
                  <span className="sr-only">needs </span>min {check.min}
                </span>
              </li>
            ))}
          </ul>
        ) : null}
      </div>

      <Collapsible.Root className="border-border border-t pt-2">
        <Collapsible.Trigger className="focus-visible:ring-ring group flex h-11 w-full cursor-pointer items-center justify-between gap-2 rounded-md text-sm font-medium focus-visible:outline-none focus-visible:ring-2">
          Advanced
          <span className="text-muted-foreground flex items-center gap-1.5 text-xs font-normal">
            every colour token
            <ChevronDownIcon
              aria-hidden
              className="duration-facade-fast ease-facade-out size-4 transition-transform group-data-[panel-open]:rotate-180"
            />
          </span>
        </Collapsible.Trigger>

        <Collapsible.Panel className="flex flex-col gap-5 pt-3">
          <div className="flex flex-col gap-2">
            <span id={`${id}-seed`} className="text-sm font-medium">
              Start from
            </span>
            <div
              role="group"
              aria-labelledby={`${id}-seed`}
              className="grid grid-cols-2 gap-1.5"
            >
              {SHIPPED_PRESETS.map((value) => (
                <Button
                  key={value}
                  variant="outline"
                  size="sm"
                  className="capitalize"
                  onClick={() => commit(seedFrom(value))}
                >
                  {value === preset ? (
                    <RotateCcwIcon aria-hidden className="size-3.5" />
                  ) : null}
                  {value}
                </Button>
              ))}
            </div>
          </div>

          <section aria-labelledby={`${id}-tokens`} className="flex flex-col gap-4">
            <h3 id={`${id}-tokens`} className="text-sm font-medium">
              Editing the {mode} palette
            </h3>
            <ul className="flex flex-col gap-4">
              {EDITABLE_TOKENS.map((token) => {
                const colour = parseOklch(palette[token])
                if (!colour) return null
                const label = TOKEN_LABELS[token]
                return (
                  <li key={token} className="flex flex-col gap-1.5">
                    <span className="flex items-center gap-2">
                      <span
                        aria-hidden
                        className="border-border size-5 shrink-0 rounded-md border"
                        style={{ background: palette[token] }}
                      />
                      <span className="text-foreground text-sm font-medium">{label}</span>
                      <DraftField
                        aria-label={`${label} hex`}
                        value={toHex(colour)}
                        onCommit={(raw) => {
                          const next = fromHex(raw)
                          // Alpha comes from the token unless the hex carries its
                          // own, so editing a translucent border stays translucent.
                          if (next) {
                            setToken(
                              token,
                              raw.trim().replace("#", "").length === 8 ||
                                raw.trim().replace("#", "").length === 4
                                ? next
                                : { ...next, a: colour.a },
                            )
                          }
                        }}
                        spellCheck={false}
                        autoCapitalize="none"
                        autoCorrect="off"
                        maxLength={9}
                        className="ml-auto w-24 text-right"
                      />
                    </span>
                    <span className="grid grid-cols-3 gap-1.5">
                      {CHANNELS.map((channel) => (
                        <span key={channel.key} className="flex items-center gap-1">
                          {/* The name comes from aria-label, so this stays a visual
                              cue only and cannot double up with it. */}
                          <span
                            aria-hidden
                            className="text-muted-foreground w-2.5 shrink-0 text-xs font-medium"
                          >
                            {channel.label}
                          </span>
                          <DraftField
                            type="number"
                            aria-label={`${label} ${channel.name}`}
                            value={String(
                              Number(colour[channel.key].toFixed(channel.places)),
                            )}
                            min={channel.min}
                            max={channel.max}
                            step={channel.step}
                            onCommit={(raw) => {
                              const next = Number(raw)
                              if (raw.trim() !== "" && Number.isFinite(next)) {
                                setToken(token, { ...colour, [channel.key]: next })
                              }
                            }}
                            className="w-full"
                          />
                        </span>
                      ))}
                    </span>
                  </li>
                )
              })}
            </ul>
          </section>
        </Collapsible.Panel>
      </Collapsible.Root>

      <div className="border-border flex flex-col items-start gap-2 border-t pt-4">
        <div className="flex w-full items-center justify-between gap-2">
          <CopyButton value={css} label="Copy CSS" />
          {stored ? (
            <Button
              variant="ghost"
              size="sm"
              className="h-8 px-2.5 text-xs"
              onClick={() => {
                setStored(null)
                setPreset(DEFAULT_PRESET)
              }}
            >
              <RotateCcwIcon aria-hidden className="size-3.5" />
              Reset
            </Button>
          ) : null}
        </div>
        <a
          href="/docs/customise"
          className="text-muted-foreground hover:text-foreground focus-visible:ring-ring rounded-md text-xs underline underline-offset-4 focus-visible:outline-none focus-visible:ring-2"
        >
          See the contrast results and how to install your theme
        </a>
      </div>
    </div>
  )
}
