"use client"

/**
 * The theme customiser's controls: edit a palette and watch the site take it.
 *
 * Built around one idea — it scores the palette against the **same pairs and
 * the same thresholds** that `scripts/check-contrast.ts` enforces in CI. A
 * customiser that happily exported a theme the build would reject is worse than
 * no customiser at all, so the checks live in `lib/theme-tokens.ts` and both
 * sides read them.
 *
 * Editing is in OKLCH rather than hex, and that is the point: lightness is the
 * axis contrast actually depends on, so dragging the L slider moves the ratio
 * predictably instead of by trial and error. The live ratio sits beside each
 * pair as you drag.
 *
 * Every edit goes through `commit`, which stores the whole `{ light, dark }`
 * pair and switches the site to the `custom` preset. There is no local draft:
 * the docs site itself — chrome, sections and preview iframes — is the preview,
 * so an edit that only moved component state would be a slider that does
 * nothing. The panel this renders in keeps its own colours pinned to the
 * shipped palette, because editing a broken theme must not break the tool you
 * are using to fix it.
 *
 * a11y of the tool itself:
 *
 *  - Every slider is an `<input type="range">` named for the token and the
 *    channel it moves ("Primary lightness"), so nineteen sliders are told
 *    apart without seeing the swatch beside them.
 *  - The failing pairs are listed as text, never signalled by colour alone.
 */

import { RotateCcwIcon } from "lucide-react"
import { useMemo } from "react"

// Generated by `scripts/extract-palettes.ts`, which the docs `registry` task
// runs. turbo.json makes typecheck, test and build depend on that task, because
// this is a static import and the file is gitignored.
import palettes from "@/.generated/palettes.json"
import { customThemeCss, useCustomTheme, type CustomTheme } from "@/lib/custom-theme"
import { contrastRatio, formatOklch, parseOklch, toHex } from "@/lib/oklch"
import {
  EDITABLE_TOKENS,
  checkPalette,
  type Palette,
  type TokenName,
} from "@/lib/theme-tokens"
import {
  SHIPPED_PRESETS,
  useActivePreset,
  useResolvedMode,
  type ShippedPreset,
} from "./theme-switcher"
import { CopyButton } from "./copy-button"
import { Badge } from "@registry/ui/badge"
import { Button } from "@registry/ui/button"

const shipped = palettes as Record<string, Palette>

const seedFrom = (preset: ShippedPreset): CustomTheme => ({
  light: { ...shipped[`${preset}-light`]! },
  dark: { ...shipped[`${preset}-dark`]! },
})

/** Human labels, so the sliders do not read as raw custom property names. */
const TOKEN_LABELS: Record<TokenName, string> = {
  "--background": "Background",
  "--foreground": "Foreground",
  "--card": "Card",
  "--card-foreground": "Card foreground",
  "--popover": "Popover",
  "--popover-foreground": "Popover foreground",
  "--primary": "Primary",
  "--primary-foreground": "Primary foreground",
  "--secondary": "Secondary",
  "--secondary-foreground": "Secondary foreground",
  "--muted": "Muted",
  "--muted-foreground": "Muted foreground",
  "--accent": "Accent",
  "--accent-foreground": "Accent foreground",
  "--destructive": "Destructive",
  "--destructive-foreground": "Destructive foreground",
  "--border": "Border",
  "--input": "Input border",
  "--ring": "Focus ring",
}

const CHANNELS = [
  { key: "l", label: "L", name: "lightness", min: 0, max: 1, step: 0.005, places: 3 },
  { key: "c", label: "C", name: "chroma", min: 0, max: 0.37, step: 0.002, places: 3 },
  {
    key: "h",
    label: "H",
    name: "hue",
    min: 0,
    max: 360,
    step: 1,
    places: 0,
    suffix: "°",
  },
] as const

interface ChannelProps {
  id: string
  label: string
  /** The full accessible name, e.g. "Primary lightness". */
  name: string
  value: number
  min: number
  max: number
  step: number
  suffix?: string
  onChange: (next: number) => void
}

function Channel({
  id,
  label,
  name,
  value,
  min,
  max,
  step,
  suffix = "",
  onChange,
}: ChannelProps) {
  return (
    <span className="flex items-center gap-2">
      {/* The name comes from aria-label, so this stays a visual cue only and
          cannot double up with it. */}
      <span
        aria-hidden
        className="text-muted-foreground w-3 shrink-0 text-xs font-medium"
      >
        {label}
      </span>
      <input
        id={id}
        type="range"
        aria-label={name}
        min={min}
        max={max}
        step={step}
        value={value}
        onChange={(event) => onChange(Number(event.target.value))}
        className="accent-primary focus-visible:ring-ring h-6 w-full cursor-pointer focus-visible:outline-none focus-visible:ring-2"
      />
      <output
        htmlFor={id}
        className="text-muted-foreground w-11 shrink-0 text-right font-mono text-xs"
      >
        {value}
        {suffix}
      </output>
    </span>
  )
}

export function ThemeCustomiser() {
  const [stored, setStored] = useCustomTheme()
  const [preset, setPreset] = useActivePreset()
  const mode = useResolvedMode()

  // Until something is stored, the starting point is whatever the site is
  // already showing, so the first drag moves the palette in front of you.
  const theme =
    stored ?? seedFrom(preset === "custom" ? "neutral" : (preset as ShippedPreset))
  const palette = theme[mode]

  /**
   * The one write path. Storing the pair and selecting the preset together is
   * what makes every control — a slider, a reseed — change the page at once.
   */
  const commit = (next: CustomTheme) => {
    setStored(next)
    if (preset !== "custom") setPreset("custom")
  }

  const updateToken = (
    token: TokenName,
    patch: Partial<{ l: number; c: number; h: number }>,
  ) => {
    const current = parseOklch(palette[token])
    if (!current) return
    commit({
      ...theme,
      [mode]: { ...palette, [token]: formatOklch({ ...current, ...patch }) },
    })
  }

  const checks = useMemo(() => checkPalette(palette, contrastRatio), [palette])
  const failures = checks.filter((check) => !check.passes)
  const css = useMemo(() => customThemeCss(theme), [theme])

  return (
    <div className="flex flex-col gap-5">
      <div className="flex flex-col gap-2">
        <span id="customiser-seed" className="text-sm font-medium">
          Start from
        </span>
        <div role="group" aria-labelledby="customiser-seed" className="flex gap-1.5">
          {SHIPPED_PRESETS.map((value) => (
            <Button
              key={value}
              variant="outline"
              size="sm"
              className="flex-1 capitalize"
              onClick={() => commit(seedFrom(value))}
            >
              {value === preset ? (
                <RotateCcwIcon aria-hidden className="size-3.5" />
              ) : null}
              {value}
            </Button>
          ))}
        </div>
      </div>

      <div className="flex flex-col gap-2">
        <Badge variant={failures.length ? "destructive" : "default"} size="sm">
          {failures.length === 0
            ? "All contrast checks pass"
            : `${failures.length} contrast ${failures.length === 1 ? "check fails" : "checks fail"}`}
        </Badge>
        {failures.length > 0 ? (
          <ul className="text-muted-foreground flex flex-col gap-1 text-xs">
            {failures.map((check) => (
              <li key={`${check.fg}-${check.bg}`} className="flex justify-between gap-2">
                <span>{check.label}</span>
                <span className="shrink-0 font-mono">
                  {check.ratio.toFixed(2)}:1 <span aria-hidden>·</span>{" "}
                  <span className="sr-only">needs </span>min {check.min}
                </span>
              </li>
            ))}
          </ul>
        ) : null}
      </div>

      <section aria-labelledby="customiser-tokens" className="flex flex-col gap-4">
        <h3 id="customiser-tokens" className="text-sm font-medium">
          Editing the {mode} palette
        </h3>
        <ul className="flex flex-col gap-4">
          {EDITABLE_TOKENS.map((token) => {
            const colour = parseOklch(palette[token])
            if (!colour) return null
            return (
              <li key={token} className="flex flex-col gap-1.5">
                <span className="flex items-center gap-2">
                  <span
                    aria-hidden
                    className="border-border size-5 shrink-0 rounded-md border"
                    style={{ background: palette[token] }}
                  />
                  <span className="text-foreground text-sm font-medium">
                    {TOKEN_LABELS[token]}
                  </span>
                  <code className="text-muted-foreground ml-auto font-mono text-xs">
                    {toHex(colour)}
                  </code>
                </span>
                {CHANNELS.map((channel) => (
                  <Channel
                    key={channel.key}
                    id={`customiser${token}-${channel.key}`}
                    label={channel.label}
                    name={`${TOKEN_LABELS[token]} ${channel.name}`}
                    value={Number(colour[channel.key].toFixed(channel.places))}
                    min={channel.min}
                    max={channel.max}
                    step={channel.step}
                    suffix={"suffix" in channel ? channel.suffix : ""}
                    onChange={(next) => updateToken(token, { [channel.key]: next })}
                  />
                ))}
              </li>
            )
          })}
        </ul>
      </section>

      <div className="border-border flex items-center justify-between gap-2 border-t pt-4">
        <CopyButton value={css} label="Copy CSS" />
        <a
          href="/docs/customise"
          className="text-muted-foreground hover:text-foreground focus-visible:ring-ring rounded-md text-xs underline underline-offset-4 focus-visible:outline-none focus-visible:ring-2"
        >
          Contrast table and how to install it
        </a>
      </div>
    </div>
  )
}
